kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: auth-mvc
  name: auth-mvc-env
data:
  NAMESPACE_NAME: {{ .Release.Namespace | quote }}
  ISTIOD_ADDR: {{ .Values.istiodAddr | quote }}
  POLLING_TIME: {{ .Values.defaultPollingTime | quote }}