== Spring Cloud Alibaba Kubernetes Config

The purpose of this module is to use Kubernetes ConfigMap/Secret as a distributed configuration center to achieve dynamic configuration updates without restarting the application.

=== Quick Start

Go to the [example](./example) and follow the docs to run the example.
You got this!

=== Main Features

If you have experience with `spring-cloud-starter-alibaba-nacos-config`, you will find out that the usage is very similar. `spring-cloud-starter-alibaba-kubernetes-config` has provided all the core features of `spring-cloud-starter-alibaba-nacos-config`, and provides more easier-to-use configurations, better performance and more in line with cloud-native.

==== Dynamic update configuration（ConfigMap/Secret）

You don't need to restart the application when the configuration is updated, and the application can dynamically update the configurations.

NOTE: Spring Cloud provides the capability of dynamically refreshing the Environment at runtime, which mainly dynamically updates the properties of two types of beans: `@ConfigurationProperties` and `@RefreshScope` beans.

*Best Practices: use `@ConfigurationProperties` to organize your configurations!*

Related configuration:

[source,yaml]
----
spring:
  cloud:
    k8s:
      config:
        refreshable: false # global default config, default value is false
        config-maps:
          - name: my-configmap
            refreshable: true # my-configmap will detect config change and refresh
        secrets:
          - name: my-secret # my-secret will NOT detect config change and refresh
----

==== Configuration priority

If there are same configurations in both local `application.yml` and ConfigMaps/Secret, you can choose which configuration to use first.

Related configuration:

[source,yaml]
----
spring:
  cloud:
    k8s:
      config:
        preference: remote # Global default config, default value is remote, means remote config will override local config
        config-maps:
          - name: my-configmap
            preference: local
----

==== Multiple configuration file formats

Supports configuration files in `yaml`, `properties`, `json` and key-value pair.

NOTE: Secret only supports key-value pair!

Example:

ConfigMap:
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  blacklist.yml: |
    blacklist:
      user-ids:
        - 1
        - 2
----

Secret:
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  blacklist.user-ids[0]: 1
  blacklist.user-ids[1]: 1
----

The two configurations above convey the same meaning.

==== Abnormal operation protection

If config was deleted by mistake, you don't want your application to crash, right? `spring-cloud-starter-alibaba-kubernetes-config` provides a mechanism to protect the application from abnormal operation, such as deleting the configuration by mistake.

Related configuration:

[source,yaml]
----
spring:
  cloud:
    k8s:
      config:
        refresh-on-deleted: false # when detect the config was deleted, the application will not trigger a refresh. Default value is false.
----

If your configuration is not synchronized across environments, and you have the `import-config` configuration in the `dev` environment but not in the `prod` environment (it is possible that you forgot to synchronize to `prod`), you may want to have a mechanism to help you find this problem and provide fail-fast ability to prevent the application from starting.

Related configuration:

[source,yaml]
----
spring:
  cloud:
    k8s:
      config:
        fail-on-missing-config: true # application will fail to start if the configs not found. Default value is true.
----

=== Core Configurations

[source,yaml]
----
spring:
  cloud:
    k8s:
      config:
        enabled: true
        namespace: default # The namespace where the configuration is located (global configuration). If inside the Kubernetes cluster, it defaults to the namespace where the current pod is located; if outside the Kubernetes cluster, it defaults to the namespace of the current context.
        preference: remote
        refreshable: false
        refresh-on-delete: false
        fail-on-missing-config: true
        config-maps:
          - name: my-configmap
            preference: remote
            refreshable: true
        secrets:
          - name: my-secret
            namespace: secret-namespace
----
