spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: 'root'
    password: 'root'
  main:
    allow-bean-definition-overriding: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true