server:
  port: 19093

spring:
  # spring application configuration
  application:
    name: routing-service-provider

  # register center configuration
  cloud:
    nacos:
      discovery:
        server-addr: sca-label-routing-nacos-server:8848
        metadata:
          version: v1
          region: dev
          zone: zone1
