version: "3"
services:
  nacos:
    container_name: nacos
    hostname: nacos
    image: nacos/nacos-server:2.0.3
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
    ports:
      - "3306:3306"
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_unicode_ci
    ]