dubbo:
  registry:
    #   The Spring Cloud Dubbo's registry extension
    ##  the default value of dubbo-provider-services is "*", that means to subscribe all providers,
    ##  thus it's optimized if subscriber specifies the required providers.
    address: spring-cloud://localhost?dubbo-provider-services=${provider.application.name}
#   The traditional Dubbo's registry
#   address: zookeeper://127.0.0.1:2181
server:
  port: 0

provider:
  application:
    name: spring-cloud-alibaba-dubbo-provider