server:
  port: 8013

spring:
  application:
    name: integrated-order
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
      config:
        server-addr: nacos-server:8848
        file-extension: yaml
        shared-configs[0]:
          dataid: datasource-config.yaml
  config:
    import:
      - optional:nacos:integrated-order.yaml?group=integrated-example
      - optional:nacos:datasource-config.yaml?group=integrated-example

seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      integrated-order-group: default
    grouplist:
      default: seata-server:8091
