#
# Copyright 2013-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: Service
metadata:
  name: integrated-mysql-web
spec:
  ports:
    - name: integrated-mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306
  type: NodePort
  selector:
    app: integrated-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: integrated-mysql
  labels:
    app: integrated-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      name: 'server'
  selector:
    app: integrated-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrated-mysql
spec:
  selector:
    matchLabels:
      app: integrated-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: integrated-mysql
    spec:
      containers:
        - name: integrated-mysql
          image: '{{ .Values.image.repository }}integrated-mysql'
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '123456'
          ports:
            - containerPort: 3306
              protocol: TCP