spring.application.name=nacos-druid-example

# import datasource config to init druid datasource.
spring.config.import[0]=optional:nacos:cipher-kms-aes-256-proxy-spring-demods001.properties?group=nacos-datasource

# nacos server address, replace it with your own
spring.cloud.nacos.config.server-addr=mse-****-p.nacos-ans.mse.aliyuncs.com

# nacos namespace, replace it with your own
spring.cloud.nacos.config.namespace=public

# nacos kms regionId , replace it with your own
spring.cloud.nacos.config.kms_region_id=cn-hangzhou

# nacos proxy druid switch and data id
spring.nacos.config.proxy.druid.enabled=true
spring.nacos.config.proxy.druid.data-id=cipher-kms-aes-256-proxy-spring-demods001.properties
