server:
  port: 18088

spring:
  application:
    name: sentinel-resttemplate-example
  cloud:
    sentinel:
      datasource:
        ds1.file:
          file: "classpath: degraderule.json"
          ruleType: "degrade"
          dataType: "json"
        ds2.file:
          file: "classpath: flowrule.json"
          ruleType: "flow"
          dataType: "json"

