server:
  port: 18088

spring:
  application:
    name: sentinel-resttemplate-example
#  Don't support run in jar by using configuration file method now, refer to https://github.com/alibaba/spring-cloud-alibaba/issues/3033
#  cloud:
#    sentinel:
#      datasource:
#        ds1.file:
#          file: "classpath: degraderule.json"
#          ruleType: "degrade"
#          dataType: "json"
#        ds2.file:
#          file: "classpath: flowrule.json"
#          ruleType: "flow"
#          dataType: "json"

