spring:
  application:
    name: integrated-consumer
  config:
    import:
      - optional:nacos:integrated-consumer.yaml?group=integrated-example
      - optional:nacos:datasource-config.yaml?group=integrated-example
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: nacos-server:8848
        shared-configs[0]:
          dataid: datasource-config.yaml
      discovery:
        server-addr: nacos-server:8848


server:
  port: 8014
