spring:
  application:
    name: integrated-consumer
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: nacos-server:8848
      discovery:
        server-addr: nacos-server:8848
  config:
    import:
      - optional:nacos:integrated-consumer.yaml?group=integrated-example
      - optional:nacos:datasource-config.yaml?group=integrated-example


server:
  port: 8014
