nacos:
  config:
    file-extension: yaml
    server-addr: nacos-server:8848
    group: integrated-example
    shared-configs[0]:
      dataid: datasource-config.yaml
      group: integrated-example
  discovery:
    server-addr: nacos-server:8848
    group: integrated-example
