seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      integrated-storage-group: default
    grouplist:
      default: seata-server:8091
