server:
  port: 18084
spring:
  application:
    name: nacos-config-example
  cloud:
    nacos:
      config:
        serverAddr: 117.72.36.124:8848
        username: 'nacos'
        password: 'nacos'
  config:
    import:
      - nacos:application-dev.yml
  profiles:
    active: dev
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug
