dubbo:
  scan:
    base-packages: org.springframework.cloud.alibaba.dubbo.examples
  protocols:
    dubbo:
      name: dubbo
      port: 12346
    rest:
      name: rest
      port: 9091
      server: netty
  registry:
    address: spring-cloud://nacos

server:
  port: 8082