server:
  port: 8012

spring:
  application:
    name: integrated-account
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        group: integrated-example
      config:
        server-addr: nacos-server:8848
        file-extension: yaml
        group: integrated-example
        shared-configs[0]:
          dataid: datasource-config.yaml
          group: integrated-example
  config:
    import:
      - optional:nacos:integrated-account.yaml?group=integrated-example
      - optional:nacos:datasource-config.yaml?group=integrated-example

seata:
  application-id: integrated-account
  tx-service-group: integrated-account-group
  service:
    vgroup-mapping:
      integrated-account-group: default
    grouplist:
      default: seata-server:8091
