server:
  port: 8012

spring:
  application:
    name: integrated-account
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        group: integrated-example
      config:
        server-addr: nacos-server:8848
        group: integrated-example
        file-extension: yaml
  config:
    import:
      - optional:nacos:integrated-account.yaml
      - optional:nacos:datasource-config.yaml

seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      integrated-account-group: default
    grouplist:
      default: seata-server:8091
