server:
  port: 30010
spring:
  application:
    name: integrated-gateway
  cloud:
    nacos:
      config:
        server-addr: nacos-server:8848
        file-extension: yaml
        group: integrated-example
      discovery:
        server-addr: nacos-server:8848
        group: integrated-example
  config:
    import: optional:nacos:integrated-gateway.yaml
