spring:
  application:
    name: integrated-provider
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: nacos-server:8848
        group: integrated-example
      discovery:
        server-addr: nacos-server:8848
        group: integrated-example
  config:
    import: optional:nacos:integrated-provider.yaml

server:
  port: 8015
