spring:
  application:
    name: integrated-provider
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: nacos-server:8848
      discovery:
        server-addr: nacos-server:8848

  config:
    import: optional:nacos:integrated-provider.yaml?group=integrated-example

server:
  port: 8015
