server:
  port: 18087

spring:
  application:
    name: service-consumer
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8081
      datasource:
        ds1.file:
          file: "classpath: degraderule.json"
          ruleType: "degrade"
          dataType: "json"
        ds2.file:
          file: "classpath: flowrule.json"
          ruleType: "flow"
          dataType: "json"

feign:
  sentinel:
    enabled: true
