server:
  port: 18087

spring:
  application:
    name: openfeign-example
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8081
#  Don't support run in jar by using configuration file method now, refer to https://github.com/alibaba/spring-cloud-alibaba/issues/3033
#      datasource:
#        ds1.file:
#          file: "classpath: degraderule.json"
#          ruleType: "degrade"
#          dataType: "json"
#        ds2.file:
#          file: "classpath: flowrule.json"
#          ruleType: "flow"
#          dataType: "json"

feign:
  sentinel:
    enabled: true
