#
# Copyright 2013-2023 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  port: 18087

spring:
  application:
    name: openfeign-example
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8081
#  Don't support run in jar by using configuration file method now, refer to https://github.com/alibaba/spring-cloud-alibaba/issues/3033
#      datasource:
#        ds1.file:
#          file: "classpath: degraderule.json"
#          ruleType: "degrade"
#          dataType: "json"
#        ds2.file:
#          file: "classpath: flowrule.json"
#          ruleType: "flow"
#          dataType: "json"

feign:
  sentinel:
    enabled: true
