dubbo:
  scan:
    base-packages: org.springframework.cloud.alibaba.dubbo.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
#   The Spring Cloud Dubbo's registry extension
    address: spring-cloud://localhost
#   The traditional Dubbo's registry
#   address: zookeeper://127.0.0.1:2181

feign:
  hystrix:
    enabled: true

server:
  port: 8080