spring:
  datasource:
    url: jdbc:mysql://integrated-mysql:3306/integrated_praise?useSSL=false&characterEncoding=utf8
  cloud:
    stream:
      function:
        definition: consumer;
      rocketmq:
        binder:
          name-server: rocketmq:9876
        bindings:
          consumer-in-0:
            consumer:
              messageModel: CLUSTERING
      bindings:
        consumer-in-0:
          destination: PRAISE-TOPIC-01
          group: praise-consumer