spring:
  cloud:
    stream:
      bindings:
        praise-output:
          destination: PRAISE-TOPIC-01
          content-type: application/json
      rocketmq:
        binder:
          name-server: rocketmq:9876
        bindings:
          praise-output:
            producer:
              group: test