server:
  port: 19097

spring:
  application:
    name: restTemplate-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: sca-label-routing-nacos-server:8848

    # label routing configuration
    governance:
      routing:
        region: dev
        zone: zone1
      # rule: RandomRule
