name: Integration Testing
on:
  push:
    branches:
      - 2023.x
      - 2025.0.x
      - 2025.1.x
  pull_request:
    branches:
      - 2023.x
      - 2025.0.x
      - 2025.1.x
jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

  integration-testing:
    name: Integration Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Dependencies Cache
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up Maven Daemon
        uses: gauthamchandra/mvnd-action@22dcb7d03ed0401ddadc760783dd9629432dff77 # v0.2.1
        with:
          # https://downloads.apache.org/maven/mvnd/
          version: '1.0.5'
      - name: "Print Maven Daemon version"
        run: mvnd -version
      - name: Compile & Checkstyle
        run: mvnd clean -B compile
      - name: install dependencies
        run: mvnd clean -B install -U package -pl '!spring-cloud-alibaba-coverage'  -DskipTests
      - name: Testing
        run: mvnd verify -B -Dmaven.test.skip=false
#        run: mvn clean -Dit.enabled=true test
      - name: Delete snapshots from the Maven local repository
        run: find ~/.m2/repository -type d -name '*-SNAPSHOT' -print -exec rm -r {} +
